name: Publish

on:
  push:
    tags:
      - v*

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: create release
        run: |
          ref=${{ github.ref }}
          tag=${ref#refs/tags/}
          echo "Hello from private repo" >> text.txt
          gh release create $tag text.txt --title "Private $tag" --generate-notes --repo sophosia/test-releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
